const countries = {
    "am-ET": "Amharic",
    "ar-SA": "Arabic",
    "be-BY": "Bielarus",
    "bem-ZM": "Bemba",
    "bi-VU": "Bislama",
    "bn-IN": "Bengali",
    "en-GB": "English",
    "de-DE": "German",
    "es-ES": "Spanish",
    "el-GR": "Greek",
    "ta-LK": "Tamil",
    "te-IN": "Telugu",
    "hi-IN": "Hindi", 
    "ja-jp": "Japanese",
    "gu-IN": "Gujarati",
    "ko-KR": "Korean",
    "fr-FR": "French",
    "ne-NP": "Nepali",
    "ur-PK": "Pakistani"
}